### ISSUE TITLE
Error with schedule/list

### ISSUE THREAD

**Issue by dbd5** [yii2mod/yii2-scheduling#2]
Hi,

The schedule/list function has a bug, please see below

./yii schedule/list
---

PHP Warning 'yii\base\ErrorException' with message 'mb_strwidth() expects parameter 1 to be string, array given'

in /var/www/app/vendor/league/climate/src/TerminalObject/Helper/StringLength.php:36

Stack trace:
#0 /var/www/app/vendor/league/climate/src/TerminalObject/Basic/Table.php(223): League\CLImate\TerminalObject\Basic\Table->lengthWithoutTags()
#1 /var/www/app/vendor/league/climate/src/TerminalObject/Basic/Table.php(192): League\CLImate\TerminalObject\Basic\Table->getCellWidth()
#2 /var/www/app/vendor/league/climate/src/TerminalObject/Basic/Table.php(65): League\CLImate\TerminalObject\Basic\Table->getColumnWidths()
#3 /var/www/app/vendor/league/climate/src/TerminalObject/Router/BasicRouter.php(28): League\CLImate\TerminalObject\Basic\Table->result()
#4 /var/www/app/vendor/league/climate/src/TerminalObject/Router/Router.php(99): League\CLImate\TerminalObject\Router\BasicRouter->execute()
#5 /var/www/app/vendor/league/climate/src/CLImate.php(381): League\CLImate\TerminalObject\Router\Router->execute()
#6 /var/www/app/vendor/league/climate/src/CLImate.php(396): League\CLImate\CLImate->buildTerminalObject()
#7 /var/www/app/vendor/league/climate/src/CLImate.php(432): League\CLImate\CLImate->routeRemainingMethod()
#8 /var/www/app/vendor/yii2mod/yii2-scheduling/ScheduleController.php(91): League\CLImate\CLImate->__call()
#9 /var/www/app/vendor/yii2mod/yii2-scheduling/ScheduleController.php(91): League\CLImate\CLImate->table()
#10 /var/www/app/vendor/yiisoft/yii2/base/InlineAction.php(57): yii2mod\scheduling\ScheduleController->actionList()
#11 /var/www/app/vendor/yiisoft/yii2/base/InlineAction.php(57): ::call_user_func_array:{/var/www/app/vendor/yiisoft/yii2/base/InlineAction.php:57}()
#12 /var/www/app/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams()
#13 /var/www/app/vendor/yiisoft/yii2/console/Controller.php(128): yii\base\Controller->runAction()
#14 /var/www/app/vendor/yiisoft/yii2/base/Module.php(523): yii\console\Controller->runAction()
#15 /var/www/app/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction()
#16 /var/www/app/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction()
#17 /var/www/app/vendor/yiisoft/yii2/base/Application.php(380): yii\console\Application->handleRequest()
#18 /var/www/app/yii(31): yii\base\Application->run()
#19 {main}

**Comment by ihorchepurnyi** [comment]
Can you show your `shedule.php` file?

**Comment by ihorchepurnyi** [comment]
I will try to fix it tomorrow

**Comment by dbd5** [comment]
This is a new install, the schedule file is literally empty - here;

`
/**
 * @var \yii2mod\scheduling\Schedule $schedule
 */

$schedule->call(function(\yii\console\Application $app) {
    /**
     * Insert command here
     */
})->everyFiveMinutes();

// $schedule->exec('ls')->everyMinute();`


Thanks

**Comment by ihorchepurnyi** [comment]
I fixed your issue, please update your package

**Comment by dbd5** [comment]
Thanks @igor-chepurnoi , its working now!

**Comment by ihorchepurnyi** [comment]
Cool!
